### ISSUE TITLE
Capacitive touch screen

### ISSUE THREAD

**Issue by bimbim2401** [wassgha/MirrorOS#34]
Hello 
Where do you place the touch screen ? Behind or in front of the two way mirror ?

Can you use a acrylic two way mirror ?

**Comment by wassgha** [comment]
I have just pushed an initial restructure of the project through #40 which details a roadmap where I believe this project should be headed and unfortunately, through experimentation I've determined that touch screens are not practical with smart mirrors because of many reasons including fingerprints, wet hands, etc. We chose to move to a more practical user interaction through a combination of voice and gestures. Currently the proof of concept implements voice and I will add gestures in the next few days.
